name: "Discord Commits"
description: "Send commit summary to Discord using custom templates"
branding:
  icon: "bell"
  color: "purple"
inputs:
  webhook_url:
    description: Discord webhook URL
  id:
    description: Discord Webhook ID (ignored if `webhook_url` is set)
  token:
    description: Discord Webhook token (ignored if `webhook_url` is set)
  repo_name:
    description: Overwrite repository name with a custom one
  censor_username:
    description: Hide the full GitHub username
    default: false
  threadID:
    description: Id of the thread if you are using threads
    default: null
  hide_links:
    description: Toggle whether to show repo links on the webhook event
    default: false
  color:
    description: Color of the Discord embed
    default: '7dbbe6'

runs:
  using: "node16"
  main: "index.js"