on: [push]

jobs:
  disord_test_message:
    runs-on: ubuntu-latest
    name: discord commits
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install NPM Dependencies (prod)
        run: npm install --frozen-lockfile --production
      - name: Send message to discord
        uses: ./ # Uses an action in the root directory
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          hide_links: true
          censor_username: false
