on: [push]

jobs:
  disord_test_message:
    runs-on: ubuntu-latest
    name: Push to Discord
    steps:

      - name: Send message to discord
        uses: ihyajb/discord-commits@test2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          hide_links: true
          censor_username: false
          color: 965fb6