on: [push]

jobs:
  disord_test_message:
    runs-on: ubuntu-latest
    name: Ajs Discord Commits
    steps:

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM Dependencies (prod)
        run: npm install
      - name: Send message to discord
        uses: ihyajb/discord-commits@main 
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          hide_links: true
          censor_username: false
