on: [push]

jobs:
  disord_test_message:
    runs-on: ubuntu-latest
    name: Ajs Discord Commits
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM Dependencies (prod)
        run: npm install --frozen-lockfile --production
      - name: Send message to discord
        uses: ./ # Uses an action in the root directory
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          hide_links: true
          censor_username: false
